boxes: # ROI区域中的BOX起始点与终止点[[(100,100), (150,150)], [(500,100), (550,150)], [(100,400), (150,450)], [(500,400), (550,450)]],需用如下方式表示
- - !!python/tuple [310,155]
  - !!python/tuple [330,175]
- - !!python/tuple [340,155]
  - !!python/tuple [360,175]
- - !!python/tuple [370,155]
  - !!python/tuple [390,175]
- - !!python/tuple [400,155]
  - !!python/tuple [420,175]
- - !!python/tuple [430,155]
  - !!python/tuple [450,175]
- - !!python/tuple [460,155]
  - !!python/tuple [480,175]
- - !!python/tuple [490,155]
  - !!python/tuple [510,175]
- - !!python/tuple [520,155]
  - !!python/tuple [540,175]
- - !!python/tuple [550,155]
  - !!python/tuple [570,175]
- - !!python/tuple [580,155]
  - !!python/tuple [600,175]

- - !!python/tuple [615,155]
  - !!python/tuple [635,175]
- - !!python/tuple [645,155]
  - !!python/tuple [665,175]
- - !!python/tuple [675,155]
  - !!python/tuple [695,175]
- - !!python/tuple [705,155]
  - !!python/tuple [725,175]
- - !!python/tuple [735,155]
  - !!python/tuple [755,175]
- - !!python/tuple [765,155]
  - !!python/tuple [785,175]
- - !!python/tuple [795,155]
  - !!python/tuple [815,175]
- - !!python/tuple [825,155]
  - !!python/tuple [845,175]
- - !!python/tuple [855,155]
  - !!python/tuple [875,175]
- - !!python/tuple [885,155]
  - !!python/tuple [905,175]

- - !!python/tuple [920,155]
  - !!python/tuple [940,175]
- - !!python/tuple [950,155]
  - !!python/tuple [970,175]
- - !!python/tuple [980,155]
  - !!python/tuple [1000,175]
- - !!python/tuple [1010,155]
  - !!python/tuple [1030,175]
- - !!python/tuple [1040,155]
  - !!python/tuple [1060,175]
- - !!python/tuple [1070,155]
  - !!python/tuple [1090,175]
- - !!python/tuple [1100,155]
  - !!python/tuple [1120,175]
- - !!python/tuple [1130,155]
  - !!python/tuple [1150,175]
- - !!python/tuple [1160,155]
  - !!python/tuple [1180,175]
- - !!python/tuple [1190,155]
  - !!python/tuple [1210,175]

- - !!python/tuple [1225,155]
  - !!python/tuple [1245,175]
- - !!python/tuple [1255,155]
  - !!python/tuple [1275,175]
- - !!python/tuple [1285,155]
  - !!python/tuple [1305,175]
- - !!python/tuple [1315,155]
  - !!python/tuple [1335,175]
- - !!python/tuple [1345,155]
  - !!python/tuple [1365,175]
- - !!python/tuple [1375,155]
  - !!python/tuple [1395,175]
- - !!python/tuple [1405,155]
  - !!python/tuple [1425,175]
- - !!python/tuple [1435,155]
  - !!python/tuple [1455,175]

- - !!python/tuple [310,215]
  - !!python/tuple [330,235]
- - !!python/tuple [355,215]
  - !!python/tuple [375,235]
- - !!python/tuple [400,215]
  - !!python/tuple [420,235]
- - !!python/tuple [445,215]
  - !!python/tuple [465,235]
- - !!python/tuple [490,215]
  - !!python/tuple [510,235]
- - !!python/tuple [535,215]
  - !!python/tuple [555,235]
- - !!python/tuple [580,215]
  - !!python/tuple [600,235]
- - !!python/tuple [625,215]
  - !!python/tuple [645,235]
- - !!python/tuple [670,215]
  - !!python/tuple [690,235]
- - !!python/tuple [715,215]
  - !!python/tuple [735,235]
- - !!python/tuple [760,215]
  - !!python/tuple [780,235]

roi: # 需要观测的区域
- - !!python/tuple [1070,1536]
  - !!python/tuple [2400,2048]
x_offset: -240 # 将所有BOX整体向x方向平移补偿值
y_offset: 0 # 将所有BOX整体向y方向平移补偿值
x_size: 0 # 将所有BOX整体在x方向增减相应值
y_size: 5 # 将所有BOX整体在y方向增减相应值
conf_enhance: 1 # 将彩色样本包括白色样本,全部作为目标颜色样本数。因某些情况下会出现中心颜色饱和（如使用导光管），至目标颜色样本不足。将全部彩色与白色样本量加入计算,将提升结果的置信度。但一般不使用置为"0"，除饱和情况严重或干扰严重时使用置为"1"。
color_threshold: 0.6 # 颜色像素占比阈值
noise_weight: 0.1 # 降低black,gray,others在计算时的权重
finetune_range: ''
is_finetune: false 